baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Helpdesk bot for Slack teams"
theme = "lunobot-theme"
googleAnalytics = ""

[params]
    [params.navigation]
        brand = "luno"

    [[menu.prepend]]
        url = "/faq"
        name = "FAQ"

    [[menu.postpend]]
        url = "https://app.lunohq.com/login"
        name = "Sign in"

    [params.hero]
        title = "A Helpdesk bot for your Slack team"
        subtitle = "Train your Lunobot to deal with common questions that you keep answering over and over again."

    [params.product]
        enable = true
        title = "Put FAQs on Autopilot"
        subtitle = "Employees can self-serve with FAQ answers from **@luno** instead of bugging you"

    [params.setup]
        enable = true
        title = "Get started in less than 10 minutes"
        subtitle = "We've made setting up Luno simple so you can get back to what you do best."

        [[params.setup.row]]

            [[params.setup.row.list]]
                icon = "emoji-computer.png"
                title = "1\\. Train your Lunobot"
                description = "Use the admin webapp to teach him the answers to common HR, IT, and other FAQs."

            [[params.setup.row.list]]
                icon = "emoji-slack.png"
                title = "2\\. Publish your Lunobot"
                description = "Invite your Lunobot to your team's dedicated help channel in Slack."

            [[params.setup.row.list]]
                icon = "emoji-tropical-drink.png"
                title = "3\\. Kick back and relax"
                description = "Watch your Lunobot work. He’ll automatically escalate questions to you if he gets stumped."

    [params.footer]
        enable = true
        copyright = "Handcrafted with ❤ in San Francisco. © Luno 2016"

        [[params.footer.quicklinks]]
            text = "Privacy Policy"
            link = "/privacy"
